version: '3.8'
services:
  website:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
      - API_PORT=81
      - HOST_API=host.docker.internal
    volumes:
      - ./website:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_net
  api:
    build: ./simple_api
    ports:
      - "81:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
