version: '3.8'

services:
  registry-ui:
    image: joxit/docker-registry-ui
    restart: always
    ports:
      - 8089:80
    environment:
      - REGISTRY_URL=http://localhost:5001
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin="['http://localhost:8089']"
    container_name: registry-ui
    networks:
      - registry-network

  registry-server:
    image: registry:2.8.2
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./registry/data:/var/lib/registry
    container_name: registry-server
    networks:
      - registry-network
networks:
  registry-network:
    driver: bridge